Feature template deserialize
CiscoDevNet/catalystwan pull request #505
Opened 2024-03-05 07:00 UTC by PrzeG

# Pull Request summary:
Adjustments to Feature Template deserialization, adding proper support for nested values and correct field names

# Description of changes:

# Checklist:
- [ ] Make sure to run pre-commit before committing changes
- [ ] Make sure all checks have passed
- [ ] PR description is clear and comprehensive
- [ ] Mentioned the issue that this PR solves (if applicable)
- [ ] Make sure you test the changes

2024-03-05 08:46 UTC, jpkrajewski commented
Please add unit tests

2024-03-05 09:04 UTC, jpkrajewski commented on catalystwan/utils/feature_template/find_template_values.py
> +def find_template_values(
The find_template_values function is integral to the UX2 transformation process. It's imperative to conduct thorough unit tests to ensure its reliability and accuracy. Testing should encompass both default Cisco models and fully populated models.

2024-03-05 14:43 UTC, jkrajew requested changes

2024-03-05 14:43 UTC, jkrajew commented on catalystwan/integration_tests/test_find_template_values.py
> +                parsed_values = find_template_values(definition)
Address the underlying issues causing the test function to fail for our demo vManage.

2024-03-05 18:04 UTC, jkrajew commented on catalystwan/integration_tests/test_find_template_values.py
> +                parsed_values = find_template_values(definition)
Please consider to write this as unit test to not rely on having fully configured vManage

2024-03-06 13:42 UTC, sbasan approved these changes

2024-03-06 13:47 UTC, jkrajew approved these changes
It's working for Demo vManage

<img width="705" alt="image" src="https://github.com/CiscoDevNet/catalystwan/assets/162307688/5140e6f3-bdf2-45e6-9bf1-60b64042125e">

2024-03-06 14:09 UTC, merged